### ISSUE TITLE
versions aren't being saved

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#1019]
Looks like some sort of an API error

```
api_1            | ValidationError: child "agentId" fails because ["agentId" must be a number]
api_1            | { error:
api_1            |    Error: not found
api_1            |        at CreatedClass.getHashAll (/usr/src/app/node_modules/nohm/ts/model.ts:1348:13)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: 'Agent id=[undefined]' }
api_1            | { error:
api_1            |    { Error: Validation failed. See .errors on this Error or the Nohm model instance for details.
api_1            |        at CreatedClass.save (/usr/src/app/node_modules/nohm/ts/model.ts:643:15)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7) modelName: 'Agent', errors: { agentName: [Array] } },
api_1            |   message: null }
api_1            | ValidationError: child "originalAgentVersionName" fails because ["originalAgentVersionName" is not allowed to be empty]
```

**Comment by dakavisa** [comment]
Closed by 80c8988eb71c039d99d3142e69e64e33667a9cce
