### ISSUE TITLE
Error editing and intents after another one was removed

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#106]
So I had `2` intents (ids `1` and `2`) and deleted `1`, now when I open the page to edit `2` I get this response from the API `An error occurred getting the data of the intent Intent1 with id 1` and this on the API console:
```
Debug: internal, implementation, error
TypeError: Uncaught error: Cannot read property 'examples' of undefined
at _.map (/Users/malave/code/spg/articulate/api/modules/domain/tools/getEntitiesCombinations.domain.tool.js:32:64)
at arrayMap (/Users/malave/code/spg/articulate/api/node_modules/lodash/lodash.js:660:23)
at Function.map (/Users/malave/code/spg/articulate/api/node_modules/lodash/lodash.js:9571:14)
at _.map (/Users/malave/code/spg/articulate/api/modules/domain/tools/getEntitiesCombinations.domain.tool.js:26:36)
at arrayMap (/Users/malave/code/spg/articulate/api/node_modules/lodash/lodash.js:660:23)
at Function.map (/Users/malave/code/spg/articulate/api/node_modules/lodash/lodash.js:9571:14)
at getCombinationOfEntities (/Users/malave/code/spg/articulate/api/modules/domain/tools/getEntitiesCombinations.domain.tool.js:20:7)
at GetDomainData (/Users/malave/code/spg/articulate/api/modules/domain/tools/buildTrainingData.domain.tool.js:17:36)
at Async.parallel (/Users/malave/code/spg/articulate/api/modules/domain/tools/getDomainData.domain.tool.js:36:16)
at /Users/malave/code/spg/articulate/api/node_modules/async/dist/async.js:3838:9
```

**Comment by wrathagom** [comment]
I tried to re-create this on intents and entities, but it looks fixed to me.
