### ISSUE TITLE
ResponseError: cluster_block_exception

### ISSUE THREAD

**Issue by jadeye** [samtecspg/articulate#1089]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
Followed your basic installation to the letter:
https://github.com/samtecspg/articulate/blob/master/docs/getting-started/basic-installation.md
- What operating system are you running?
Ubuntu 18.04
- Are you running locally or in the cloud?
locally
- Which browser are you using?
Chrome-stable, Opera, Chromium, FF
----
For a while I got:
`elasticsearch low disk watermark [85%] exceeded on`
(articulate did work before despite the errors)
I cleared space on drive but now it does not function at all.

These are the errors I'm getting:
```
nginx_1          | 172.18.0.1 - - [15/Aug/2020:19:20:58 +0000] "GET /api/ HTTP/1.1" 502 560 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
nginx_1          | 2020/08/15 19:21:04 [error] 9#9: *478 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.4:7500/", host: "localhost:8080"
nginx_1          | 172.18.0.1 - - [15/Aug/2020:19:21:04 +0000] "GET /api/ HTTP/1.1" 502 560 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
api_1            | yarn run v1.22.4
api_1            | $ cross-env NODE_ENV=production env-cmd server/.env babel-node server
api_1            | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
api_1            | Server started at http://0.0.0.0:7500
api_1            | Documentation at http://0.0.0.0:7500/documentation
api_1            | /usr/src/app/server/index.js:59
api_1            |     throw err;
api_1            |     ^
api_1            | 
api_1            | ResponseError: cluster_block_exception
api_1            |     at IncomingMessage.response.on (/usr/src/app/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
api_1            |     at IncomingMessage.emit (events.js:203:15)
api_1            |     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
api_1            |     at endReadableNT (_stream_readable.js:1145:12)
api_1            |     at process._tickCallback (internal/process/next_tick.js:63:19)
api_1            | error Command failed with exit code 1.
api_1            | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_1            | 2020/08/15 17:51:53 Command exited with error: exit status 1
api_1            | 2020/08/15 17:52:45 Waiting for: http://elasticsearch:9200
api_1            | 2020/08/15 17:52:45 Received 200 from http://elasticsearch:9200
api_1            | yarn run v1.22.4
api_1            | $ cross-env NODE_ENV=production env-cmd server/.env babel-node server
api_1            | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
api_1            | Server started at http://0.0.0.0:7500
api_1            | Documentation at http://0.0.0.0:7500/documentation
api_1            | /usr/src/app/server/index.js:59
api_1            |     throw err;
nginx_1          | 2020/08/15 19:21:16 [error] 9#9: *480 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.4:7500/", host: "localhost:808



api_1            | yarn run v1.22.4
api_1            | $ cross-env NODE_ENV=production env-cmd server/.env babel-node server
api_1            | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
elasticsearch_1  | {"type": "server", "timestamp": "2020-08-15T20:02:10,709+0000", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "e14b63952c40", "cluster.uuid": "otjAGUykRKCt40OdOEnGFg", "node.id": "Rno8q8VwTZWXAxyu88O7gg",  "message": "adding template [document_template] for index patterns [document*]"  }
api_1            | Server started at http://0.0.0.0:7500
api_1            | Documentation at http://0.0.0.0:7500/documentation
api_1            | /usr/src/app/server/index.js:59
api_1            |     throw err;
api_1            |     ^
api_1            | 
api_1            | ResponseError: cluster_block_exception
api_1            |     at IncomingMessage.response.on (/usr/src/app/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
api_1            |     at IncomingMessage.emit (events.js:203:15)
api_1            |     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
api_1            |     at endReadableNT (_stream_readable.js:1145:12)
api_1            |     at process._tickCallback (internal/process/next_tick.js:63:19)
api_1            | error Command failed with exit code 1.
api_1            | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_1            | 2020/08/15 20:02:12 Command exited with error: exit status 1
articulate-100_api_1 exited with code 1
api_1            | yarn run v1.22.4
api_1            | $ cross-env NODE_ENV=production env-cmd server/.env babel-node server
api_1            | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
elasticsearch_1  | {"type": "server", "timestamp": "2020-08-15T20:03:15,374+0000", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "e14b63952c40", "cluster.uuid": "otjAGUykRKCt40OdOEnGFg", "node.id": "Rno8q8VwTZWXAxyu88O7gg",  "message": "adding template [document_template] for index patterns [document*]"  }
api_1            | Server started at http://0.0.0.0:7500
api_1            | Documentation at http://0.0.0.0:7500/documentation
api_1            | /usr/src/app/server/index.js:59
api_1            |     throw err;
api_1            |     ^
api_1            | 
api_1            | ResponseError: cluster_block_exception
api_1            |     at IncomingMessage.response.on (/usr/src/app/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
api_1            |     at IncomingMessage.emit (events.js:203:15)
api_1            |     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
api_1            |     at endReadableNT (_stream_readable.js:1145:12)
api_1            |     at process._tickCallback (internal/process/next_tick.js:63:19)
api_1            | error Command failed with exit code 1.
api_1            | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_1            | 2020/08/15 20:03:17 Command exited with error: exit status 1
articulate-100_api_1 exited with code 1
api_1            | yarn run v1.22.4
api_1            | $ cross-env NODE_ENV=production env-cmd server/.env babel-node server
api_1            | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
elasticsearch_1  | {"type": "server", "timestamp": "2020-08-15T20:04:20,057+0000", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "e14b63952c40", "cluster.uuid": "otjAGUykRKCt40OdOEnGFg", "node.id": "Rno8q8VwTZWXAxyu88O7gg",  "message": "adding template [document_template] for index patterns [document*]"  }
api_1            | Server started at http://0.0.0.0:7500
api_1            | Documentation at http://0.0.0.0:7500/documentation
api_1            | /usr/src/app/server/index.js:59
api_1            |     throw err;
api_1            |     ^
api_1            | 
api_1            | ResponseError: cluster_block_exception
api_1            |     at IncomingMessage.response.on (/usr/src/app/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
api_1            |     at IncomingMessage.emit (events.js:203:15)
api_1            |     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
api_1            |     at endReadableNT (_stream_readable.js:1145:12)
api_1            |     at process._tickCallback (internal/process/next_tick.js:63:19)
api_1            | error Command failed with exit code 1.
api_1            | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_1            | 2020/08/15 20:04:21 Command exited with error: exit status 1

```

**Comment by jadeye** [comment]
Only god can judge me now ;-)
In some miraculous way it's working...mmm
