### ISSUE TITLE
Odd Error during Converse

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#110]
My guess is that this has to do with the fact that I have a domain with no intents:

```
api_1       | Debug: internal, implementation, error
api_1       |     TypeError: Uncaught error: Cannot read property 'intentName' of undefined
api_1       |     at server.inject (/usr/src/app/modules/agent/tools/getAvailableDomains.agent.tool.js:52:122)
api_1       |     at Shot.inject (/usr/src/app/node_modules/hapi/lib/connection.js:327:16)
api_1       |     at process.nextTick (/usr/src/app/node_modules/shot/lib/response.js:26:36)
api_1       |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
api_1       |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
api_1       | Debug: internal, implementation, error
api_1       |     TypeError: Uncaught error: Cannot read property 'intentName' of undefined
api_1       |     at server.inject (/usr/src/app/modules/agent/tools/getAvailableDomains.agent.tool.js:52:122)
api_1       |     at Shot.inject (/usr/src/app/node_modules/hapi/lib/connection.js:327:16)
api_1       |     at process.nextTick (/usr/src/app/node_modules/shot/lib/response.js:26:36)
api_1       |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
api_1       |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
api_1       | Debug: internal, implementation, error
api_1       |     TypeError: Uncaught error: Cannot read property 'intentName' of undefined
api_1       |     at server.inject (/usr/src/app/modules/agent/tools/getAvailableDomains.agent.tool.js:52:122)
api_1       |     at Shot.inject (/usr/src/app/node_modules/hapi/lib/connection.js:327:16)
api_1       |     at process.nextTick (/usr/src/app/node_modules/shot/lib/response.js:26:36)
api_1       |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
api_1       |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by dcalvom** [comment]
Yep it seem so. I was able to reproduce it. I will fix it soon.

**Comment by dcalvom** [comment]
Fixed by https://github.com/samtecspg/articulate/commit/adfd618e6133de7ca169e9c45c892bf73e1ff98c
