### ISSUE TITLE
Training with rasa sometimes fails.

### ISSUE THREAD

**Issue by Johnz86** [samtecspg/articulate#206]
### Issues
On longer running articulate stack, creation of intent fails on rasa training. 
By longer running stack I mean horizont of 2 days : - )

### Environment
Articulate version:  0.8
RasaNLU: 0.11.4

Docker Setups is done in aws linux vm.
```
NAME="Amazon Linux"
VERSION="2 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (2017.12) LTS Release Candidate
```
Errors in logs:
```
rasa_1      | INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
rasa_1      | 2018-05-16 11:45:56+0000 [-] Unhandled Error
rasa_1      |   Traceback (most recent call last):
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 500, in errback
rasa_1      |       self._startRunCallbacks(fail)
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
rasa_1      |       self._runCallbacks()
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
rasa_1      |       current.result = callback(current.result, *args, **kw)
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
rasa_1      |       _inlineCallbacks(r, g, deferred)
rasa_1      |   --- <exception caught here> ---
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
rasa_1      |       result = result.throwExceptionIntoGenerator(g)
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
rasa_1      |       return g.throw(self.type, self.value, self.tb)
rasa_1      |     File "/app/rasa_nlu/server.py", line 205, in train
rasa_1      |       data_string, kwargs)
rasa_1      |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
rasa_1      |       current.result = callback(current.result, *args, **kw)
rasa_1      |     File "rasa_nlu/data_router.py", line 224, in training_errback
rasa_1      |       target_project = self.project_store.get(failure.value.failed_target_project)
rasa_1      |   exceptions.AttributeError: 'exceptions.IndexError' object has no attribute 'failed_target_project'
rasa_1      |
rasa_1      | 2018-05-16 11:45:56+0000 [-] "172.18.0.2" - - [16/May/2018:11:45:56 +0000] "POST /train?language=en&project=Sara-CSML&fixed_model_name=SmallTalk_6e8ab66b-f601-954f-8ddf-db917c4c16c7 HTTP/1.1" 500 5772 "-" "-"
api_1       | Debug: internal, implementation, error
api_1       |     Error: An error occurred calling the training process.
api_1       |     at Wreck.post (/usr/src/app/modules/domain/tools/retrainModel.domain.tool.js:25:36)
api_1       |     at read (/usr/src/app/node_modules/wreck/lib/index.js:530:24)
api_1       |     at finish (/usr/src/app/node_modules/wreck/lib/index.js:350:20)
api_1       |     at wrapped (/usr/src/app/node_modules/hoek/lib/index.js:871:20)
api_1       |     at module.exports.internals.Recorder.onReaderFinish (/usr/src/app/node_modules/wreck/lib/index.js:421:16)
api_1       |     at Object.onceWrapper (events.js:291:19)
api_1       |     at emitNone (events.js:91:20)
api_1       |     at module.exports.internals.Recorder.emit (events.js:186:7)
api_1       |     at finishMaybe (_stream_writable.js:510:14)
api_1       |     at afterWrite (_stream_writable.js:384:3)
```
or:
```
rasa_1      | INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
rasa_1      | 2018-05-16 11:18:13+0000 [-] Traceback (most recent call last):
rasa_1      | 2018-05-16 11:18:13+0000 [-]   File "preshed/maps.pyx", line 85, in preshed.maps.PreshMap.set (preshed/maps.cpp:2752)
rasa_1      | 2018-05-16 11:18:13+0000 [-]   File "preshed/maps.pyx", line 126, in preshed.maps.map_set (preshed/maps.cpp:3241)
rasa_1      | 2018-05-16 11:18:13+0000 [-]   File "preshed/maps.pyx", line 205, in preshed.maps._resize (preshed/maps.cpp:4026)
rasa_1      | 2018-05-16 11:18:13+0000 [-]   File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
rasa_1      | 2018-05-16 11:18:13+0000 [-] MemoryError: Error assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytes
rasa_1      | 2018-05-16 11:18:13+0000 [-] Exception MemoryError: MemoryError('Error assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytesError assigning 4194304 bytes',) in 'spacy.strings.StringStore._intern_utf8' ignored
```
After the creation fails, I need to reload the intent in UI, modify it and then I can update the intent.
Problems is, when the rasa stack fails on some memory issues. Then nothing helps and I need to botstrap the entire stack from scratch, because rasa will allways fail during training of any Intent.
The memory issue occur even, when my training data is still very small (like 4 intents) and the VM running docker has 4GB of ram. According the docker stats the stack consumes around 70% of available memory at most.

**Comment by wrathagom** [comment]
How long is longer running? Any idea how many training/testing cycles you had gone through?
in 0.8 old models never get removed from memory (Rasa just recently exposed the functionality to do this). So in 0.9 we updated to Rasa 0.12.3 and we do now unload old models from memory. Maybe once @milutz get's 0.9 released #205  that will be the easiest fix.

We have other things going on for longer running training, like detaching training from intent creation #198. But none of that will help if you're still running out of memory. We have tossed around the idea of  introducing functionality to automatically spin up powerful cloud VMs on demand for training, which could be used on smaller memory instances.

**Comment by Johnz86** [comment]
According the ```docker ps -a```, the stack was running like 48 hours. And rasa was consuming around 70% percent of memory (3GB).  
I tried to restart the rasa container, but that did not much help. The consumption of memory went up to the same numbers, after just two trainings. The intent training started to fail again. 
I consider this as a solution that is not suitable for longer running setups.
Maybe after 0.9.0 is released it will be usable :)

**Comment by Johnz86** [comment]
I pulled today version 0.9.1 from docker hub. I have still errors like:
```
rasa_1      | 2018-05-18 08:06:17+0000 [-] "172.18.0.6" - - [18/May/2018:08:06:17 +0000] "POST /parse HTTP/1.1" 200 640 "-" "-"
rasa_1      | 2018-05-18 08:12:40+0000 [-] 2018-05-18 08:12:40 ERROR    rasa_nlu.train  - Failed to train project 'Sara-CSML'.
rasa_1      | 2018-05-18 08:12:40+0000 [-] Traceback (most recent call last):
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/train.py", line 120, in do_train_in_worker
rasa_1      | 2018-05-18 08:12:40+0000 [-]     component_builder)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/train.py", line 143, in do_train
rasa_1      | 2018-05-18 08:12:40+0000 [-]     trainer = Trainer(cfg, component_builder)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/model.py", line 149, in __init__
rasa_1      | 2018-05-18 08:12:40+0000 [-]     self.pipeline = self._build_pipeline(cfg, component_builder)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/model.py", line 160, in _build_pipeline
rasa_1      | 2018-05-18 08:12:40+0000 [-]     component_name, cfg)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/components.py", line 420, in create_component
rasa_1      | 2018-05-18 08:12:40+0000 [-]     cfg)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/registry.py", line 140, in create_component_by_name
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return component_clz.create(config)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "rasa_nlu/utils/spacy_utils.py", line 73, in create
rasa_1      | 2018-05-18 08:12:40+0000 [-]     nlp = spacy.load(spacy_model_name, parser=False)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/__init__.py", line 19, in load
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return util.load_model(name, **overrides)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/util.py", line 112, in load_model
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return load_model_from_link(name, **overrides)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/util.py", line 131, in load_model_from_link
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return cls.load(**overrides)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/data/en/__init__.py", line 12, in load
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return load_model_from_init_py(__file__, **overrides)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/util.py", line 176, in load_model_from_init_py
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return load_model_from_path(data_path, meta, **overrides)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/util.py", line 158, in load_model_from_path
rasa_1      | 2018-05-18 08:12:40+0000 [-]     return nlp.from_disk(model_path)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/language.py", line 629, in from_disk
rasa_1      | 2018-05-18 08:12:40+0000 [-]     util.from_disk(path, deserializers, exclude)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/util.py", line 521, in from_disk
rasa_1      | 2018-05-18 08:12:40+0000 [-]     reader(path / key)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "/usr/lib/python2.7/site-packages/spacy/language.py", line 616, in <lambda>
rasa_1      | 2018-05-18 08:12:40+0000 [-]     ('vocab', lambda p: self.vocab.from_disk(p)),
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "vocab.pyx", line 373, in spacy.vocab.Vocab.from_disk
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "vocab.pyx", line 374, in spacy.vocab.Vocab.from_disk
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "vocab.pyx", line 466, in spacy.vocab.Vocab.lexemes_from_bytes
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "preshed/maps.pyx", line 85, in preshed.maps.PreshMap.set (preshed/maps.cpp:2752)
rasa_1      | 2018-05-18 08:12:40+0000 [-]     map_set(self.mem, self.c_map, key, <void*>value)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "preshed/maps.pyx", line 126, in preshed.maps.map_set (preshed/maps.cpp:3241)
rasa_1      | 2018-05-18 08:12:40+0000 [-]     _resize(mem, map_)
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "preshed/maps.pyx", line 205, in preshed.maps._resize (preshed/maps.cpp:4026)
rasa_1      | 2018-05-18 08:12:40+0000 [-]     map_.cells = <Cell*>mem.alloc(new_size, sizeof(Cell))
rasa_1      | 2018-05-18 08:12:40+0000 [-]   File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
rasa_1      | 2018-05-18 08:12:40+0000 [-]     raise MemoryError("Error assigning %d bytes" % number * elem_size)
rasa_1      | 2018-05-18 08:12:40+0000 [-] MemoryError: Error assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytes
rasa_1      | 2018-05-18 08:12:41+0000 [-] 2018-05-18 08:12:41 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.TrainingException'>: Error assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytesError assigning 1048576 bytes
rasa_1      | 2018-05-18 08:12:41+0000 [-] ]
rasa_1      | 2018-05-18 08:12:41+0000 [-] "172.18.0.6" - - [18/May/2018:08:12:40 +0000] "POST /train?project=Sara-CSML&model=SmallTalk_48d7e768-f29b-003f-18ae-b0dbb7dbe1eb HTTP/1.1" 500 481 "-" "-"
```
And the UI behaves in a strange way. When I switch between intents, sometimes I have content from previously opened intent displayed.

**Comment by wrathagom** [comment]
I haven't tested 0.9.1 yet, Are you re-training your model? Or is this a model you had trained previously you are trying to reload?

**Comment by wrathagom** [comment]
@Johnz86 did you train it on your Fedora machine? Or did you train it on a Mac and then upload to your VM?

I may be wrong, but I am curious if this isn't some sort of a pickling/architecture problem. I have no problems running your zip file.

But the models Rasa NLU generated aren't generally speaking transferable. There are a lot of things from architectures to python versions that can cause them to not be compatible with different machines. Can you try using the export from your agent to import into the new machine and thus re-training to see if the problem persists?

Here's the export https://gist.github.com/wrathagom/dd123511854f7a8a6fb2966f281c2b5e

go to http://localhost:7500/documentation#!/agent/postAgentImport to try and import it.

**Comment by wrathagom** [comment]
@Johnz86 I also took an in-depth look at memory usage today. By default, we allow 4 training process. These process each load the spacy language model when they are started. and they never go away (they just wait for more training requests). Running on a server with just 4G of ram, I would recommend reducing the number of training processes to 2.

This is controlled by the Rasa Docker file, for which you'll need to modify the command. We'll probably reduce the default number in the next release.

**Comment by dcalvom** [comment]
Hi @Johnz86, whenever you try to import an agent please be sure you exported your agent setting the flag withReferences to false. Like in the following image:

![image](https://user-images.githubusercontent.com/7228045/40350713-d11d39a6-5d67-11e8-9613-16ebe7e56edd.png)

I apologize for this inconvenient as we know this should be written somewhere. We hope in the feature include this feature in the UI so the user doesn't have to be conscious of the proper usage of this flag.

**Comment by dcalvombl** [comment]
Sure. I will default to false.

I use it for development purpose to know the id of my domains and intents as exports let me know visually which one are related

**Comment by Johnz86** [comment]
Hi, I did increase the amount of ram to 8GB, after that, I am no longer suffering from memory issues in longer running instance. Current setup is running for a week. After today training with newest version of articulate still works. This issue can be closed.

**Comment by wrathagom** [comment]
Thanks @Johnz86
