### ISSUE TITLE
TypeError: Uncaught error: Cannot read property 'entityText' of undefined

### ISSUE THREAD

**Issue by BHARATHPABBA** [samtecspg/articulate#285]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.
TypeError: Uncaught error: Cannot read property 'entityText' of undefined
api_1 | at entitiesList.forEach (/usr/src/app/modules/domain/tools/buildDomainRecognitionTrainingData.domain.tool.js:59:75)
api_1 | at Array.forEach (native)
api1 | at .map (/usr/src/app/modules/domain/tools/buildDomainRecognitionTrainingData.domain.tool.js:57:46)
api_1 | at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1 | at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api1 | at .map (/usr/src/app/modules/domain/tools/buildDomainRecognitionTrainingData.domain.tool.js:49:54)
api_1 | at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1 | at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api1 | at .uniq..flatten..map (/usr/src/app/modules/domain/tools/buildDomainRecognitionTrainingData.domain.tool.js:33:51)
api_1 | at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1 | at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api_1 | Debug: internal, implementation, error
api_1 | TypeError: Uncaught error: Cannot read property 'entityText' of undefined
api_1 | at entitiesList.forEach (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:48:71)
api_1 | at Array.forEach (native)
api1 | at .map (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:46:42)
api_1 | at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1 | at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api1 | at .map (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:38:50)
api_1 | at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1 | at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api1 | at .uniq..flatten..map (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:22:47)
api_1 | at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1 | at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14
- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by BHARATHPABBA** [comment]
Thanks to Daniel Calvo Marin for resolving this issue at gitter.

Solution: By just avoiding or removing duplicates for same value.
Remove your Duplicates It should work good. Duplicate example:
 {
          "userSays": "Is your pizza good?",
          "entities": [
            {
              "end": 22,
              "start": 8,
              "value": "pizza good",
              "entity": "happy"
            },
            {
              "end": 22,
              "start": 13,
              "value": "good",
              "entity": "happy"
            }
          ]
        }
