### ISSUE TITLE
articulate-master_rasa_1 exited with code 1

### ISSUE THREAD

**Issue by ilysorc** [samtecspg/articulate#346]
When I run the application with docker-compose up rasa is giving error. Anybody has experienced this problem?

- Did you download a release or pull from Master? Which release? **Master**
- What operating system are you running? **Windows 10**
- Are you running locally or in the cloud? **Local**
- Which browser are you using? **Google Chrome**

Error Details;

rasa_1      | Traceback (most recent call last):
rasa_1      |   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
rasa_1      |     "__main__", fname, loader, pkg_name)
rasa_1      |   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
rasa_1      |     exec code in run_globals
rasa_1      |   File "/app/rasa_nlu/server.py", line 438, in <module>
rasa_1      |     wait_time_between_pulls=cmdline_args.wait_time_between_pulls
rasa_1      |   File "rasa_nlu/data_router.py", line 109, in __init__
rasa_1      |     self.project_store = self._create_project_store(project_dir)
rasa_1      |   File "rasa_nlu/data_router.py", line 177, in _create_project_store
rasa_1      |     self.remote_storage)
rasa_1      |   File "rasa_nlu/project.py", line 180, in __init__
rasa_1      |     self._search_for_models()
rasa_1      |   File "rasa_nlu/project.py", line 344, in _search_for_models
rasa_1      |     model_names = (self._list_models_in_dir(self._path) +
rasa_1      |   File "rasa_nlu/project.py", line 429, in _list_models_in_dir
rasa_1      |     for model in utils.list_subdirectories(path)]
rasa_1      |   File "rasa_nlu/utils/__init__.py", line 126, in list_subdirectories
rasa_1      |     for fn in glob.glob(os.path.join(path, '*'))
rasa_1      |   File "/usr/lib/python2.7/posixpath.py", line 73, in join
rasa_1      |     path += '/' + b
rasa_1      | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
rasa_1      | Exception AttributeError: "'DataRouter' object has no attribute 'pool'" in <bound method DataRouter.__del__ of <rasa_nlu.data_router.DataRouter object at 0x7fad743a1a50>> ignored
articulate-master_rasa_1 exited with code 1

![image](https://user-images.githubusercontent.com/2563790/46992897-1c0e0780-d115-11e8-8627-fe3b088962f6.png)

**Comment by wrathagom** [comment]
Sorry @ilysorc for missing this one. I'll try to review the Rasa repo to see if I can find this issue over there.

Are you by any chance using a custom config file? Also have you tried running the `docker-compose up` command from straight command prompt/powershell. Looks like you may be using some other terminal.
