### ISSUE TITLE
Removing all sayings from a domain causes training/conversing to fail

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#407]
Create an agent with at least 2 domains and sayings/actions attached to both and train your agent.

Now delete all the sayings attached to one of the domains.

I saw two things, one sometimes the after deleting the sayings and hitting train, the agent would immeadietly say `last trained: just now` without having taken any time to train. Whenever this happens I get this error in the terminal when trying to converse with he agent:

```
api_1_b1a09db8c773 | { error:
api_1_b1a09db8c773 |    { isHandled: true,
api_1_b1a09db8c773 |      statusCode: 500,
api_1_b1a09db8c773 |      message: 'firstDomainSaying.actions.join is not a function' },
api_1_b1a09db8c773 |   message: null }
```

I also saw this error in the console when training would fail:
```
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-] /usr/lib/python2.7/site-packages/sklearn/model_selection/_split.py:605: exceptions.Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-] 2018-11-27 02:46:04 ERROR    rasa_nlu.train  - Failed to train project 'test'.
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-] Traceback (most recent call last):
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "rasa_nlu/train.py", line 120, in do_train_in_worker
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     component_builder)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "rasa_nlu/train.py", line 149, in do_train
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     interpreter = trainer.train(training_data, **kwargs)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "rasa_nlu/model.py", line 190, in train
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     **context)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "rasa_nlu/classifiers/sklearn_intent_classifier.py", line 130, in train
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     self.clf.fit(X, y)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 639, in fit
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     cv.split(X, y, groups)))
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     while self.dispatch_one_batch(iterator):
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     self._dispatch(tasks)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     job = self._backend.apply_async(batch, callback=cb)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     result = ImmediateResult(func)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     self.results = batch()
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     return [func(*args, **kwargs) for func, args, kwargs in self.items]
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 458, in _fit_and_score
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     estimator.fit(X_train, y_train, **fit_params)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/svm/base.py", line 150, in fit
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     y = self._validate_targets(y)
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn/svm/base.py", line 506, in _validate_targets
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-]     % len(cls))
rasa_1_f69a4fd0127b | 2018-11-27 02:46:04+0000 [-] ValueError: The number of classes has to be greater than one; got 1
rasa_1_f69a4fd0127b | 2018-11-27 02:46:06+0000 [-] 2018-11-27 02:46:06 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class'rasa_nlu.train.TrainingException'>: The number of classes has to be greater than one; got 1
```

**Comment by dcalvom** [comment]
@malave would you mind to take this one? Seems like an API issue?

**Comment by malave** [comment]
@dcalvom got it. I'll check it out.
