### ISSUE TITLE
docker  AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by Ajinkz** [samtecspg/articulate#438]
ajinkya@VirtualBox:~/articulate$ docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/home/ajinkya/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ajinkya/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/home/ajinkya/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/home/ajinkya/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 14, in <module>
    from . import errors
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 9, in <module>
    from docker.errors import APIError
  File "/home/ajinkya/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/ajinkya/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/ajinkya/.local/lib/python2.7/site-packages/docker/api/client.py", line 5, in <module>
    import requests
  File "/home/ajinkya/.local/lib/python2.7/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/ajinkya/.local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by wrathagom** [comment]
This doesn’t look like an Articulate problem, but rather a Docker problem. Can you tell us which version of Docker you have installed, how you installed it, and where (OS) it’s installed?

**Comment by wrathagom** [comment]
I would recommend trying something like this in your virtual box.

https://github.com/EmpireProject/Empire/issues/429#issuecomment-275199239

**Comment by Ajinkz** [comment]
Yes I'm trying this on virtual machine only

**Comment by wrathagom** [comment]
Were you able to try the fix above?

**Comment by Ajinkz** [comment]
yes , I fix that error but now facing error in fetching its files, I tried it for several times but each time it happen to stop. 
![image](https://user-images.githubusercontent.com/11535456/49927944-19494c00-fee5-11e8-9bf6-59572e575a86.png)
Please do suggest some alternative way to install articulate.

**Comment by wrathagom** [comment]
@Ajinkz I don't know if that problem is your internet or Docker Hub issues. I would recommend trying again today to see if it is any better. You could also try to pull them in pieces with `docker-compose pull api` `docker-compose pull ui` etc until you have all of them.

If your internet still isn't cooperating I can provide you with a cloud instance to test with.

**Comment by Ajinkz** [comment]
Ok sure I will try once again

**Comment by spg-matt** [comment]
@Ajinkz, please let us know if you were ever able to get this working.

**Comment by dcalvom** [comment]
Closed since there has not been any recent activity. Please open a new issue for related bugs.

**Comment by parasjain1** [comment]
In case someone's still looking for a fix, updating pyopenssl version via `pip install --upgrade pyopenssl` solves the issue.

**Comment by renjupauljosev** [comment]
As @parasjain1 said, confirming that `pip install --upgrade pyopenssl` fixed the issue for me.

Thanks mate.
