### ISSUE TITLE
Highlighting entities clears the sayings list

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#481]
Highlighting entities clears the sayings page. This may be related to the sayings search functionality being broken. The following error is shown in the browser console:

```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (saying, line 0)
```

The following error is shown in the terminal:

```
api_1            | { ValidationError: child "filter" fails because ["filter" must be an object]
api_1            |     at Object.exports.process (/usr/src/app/node_modules/joi/lib/errors.js:196:19)
api_1            |     at internals.Object._validateWithOptions (/usr/src/app/node_modules/joi/lib/types/any/index.js:675:31)
api_1            |     at module.exports.internals.Any.root.validate (/usr/src/app/node_modules/joi/lib/index.js:138:23)
api_1            |     at Object.internals.input (/usr/src/app/node_modules/hapi/lib/validation.js:83:63)
api_1            |     at exports.query (/usr/src/app/node_modules/hapi/lib/validation.js:56:22)
api_1            |     at Request._lifecycle (/usr/src/app/node_modules/hapi/lib/request.js:262:62)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            |   isJoi: true,
api_1            |   name: 'ValidationError',
api_1            |   details:
api_1            |    [ { message: '"filter" must be an object',
api_1            |        path: [Array],
api_1            |        type: 'object.base',
api_1            |        context: [Object] } ],
api_1            |   _object:
api_1            |    { loadCategoryId: 'true',
api_1            |      skip: '0',
api_1            |      limit: '5',
api_1            |      direction: 'DESC',
api_1            |      field: 'id',
api_1            |      filter: '"[object Object]"' },
api_1            |   annotate: [Function],
api_1            |   isBoom: true,
api_1            |   isServer: false,
api_1            |   data: null,
api_1            |   output:
api_1            |    { statusCode: 400,
api_1            |      payload:
api_1            |       { statusCode: 400,
api_1            |         error: 'Bad Request',
api_1            |         message: 'child "filter" fails because ["filter" must be an object]',
api_1            |         validation: [Object] },
api_1            |      headers: {} },
api_1            |   reformat: [Function] }
```

**Comment by wrathagom** [comment]
Worked fine for me.
