### ISSUE TITLE
Error when trying to use .original in slots

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#548]
Here's the error:
```
api_1            | TypeError: Cannot use 'in' operator to search for 'original' in undefined
api_1            |     at Object.strict (/usr/src/app/node_modules/handlebars/lib/handlebars/runtime.js:74:17)
api_1            |     at Object.eval (eval at createFunctionContext (/usr/src/app/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:236:23), <anonymous>:3:64)
api_1            |     at main (/usr/src/app/node_modules/handlebars/lib/handlebars/runtime.js:152:32)
api_1            |     at ret (/usr/src/app/node_modules/handlebars/lib/handlebars/runtime.js:155:12)
api_1            |     at ret (/usr/src/app/node_modules/handlebars/lib/handlebars/compiler/compiler.js:513:21)
api_1            |     at compiledResponse (/usr/src/app/lib/services/agent/agent.converse-compile-response-templates.service.js:14:36)
api_1            |     at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:639:23)
api_1            |     at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9554:14)
api_1            |     at AgentService.map (/usr/src/app/lib/services/agent/agent.converse-compile-response-templates.service.js:7:29)
api_1            |     at AgentService.apply [as converseCompileResponseTemplates] (/usr/src/app/lib/services/agent.services.js:257:55)
```

Here is the conversation:
![image](https://user-images.githubusercontent.com/1779894/52317999-71a24480-2990-11e9-9c5b-697248d07999.png)

here is the export:
https://gist.github.com/wrathagom/90cc0446151554fc3d844c79ed430e9c

**Comment by dcalvom** [comment]
The slotName is `date` you are using `slots.data...` in the response

```
{
      "actionName": "Hours",
      "slots": [
        {
          "slotName": "date",
          "uiColor": "#009688",
          "keyword": "sys.duckling_time",
          "keywordId": 0,
          "isList": false,
          "isRequired": false,
          "textPrompts": []
        }
      ],
      "responses": [
        {
          "textResponse": "{{slots.data.original}} we are open from 11Am until 11PM.",
          "actions": []
        },
        {
          "textResponse": "We are open from 11AM until 11PM tomorrow.",
          "actions": []
        },
        {
          "textResponse": "We're open everyday from 11AM to 11PM.",
          "actions": []
        }
      ],
      "useWebhook": false,
      "usePostFormat": false,
      "creationDate": "1549420321000",
      "modificationDate": "1549421231000"
    }
```

Please let me know if that is the issue

**Comment by wrathagom** [comment]
Doh
