### ISSUE TITLE
Chrome: Getting blank page when exiting from slots page after prompt.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#671]
Please describe the issue you are having here and answer the question below.

When I exited from slots page, after hitting save when a value box is blank and hitting exit, then prompt coming up and chosing "Exit" it goes to a blank screen. 

![image](https://user-images.githubusercontent.com/42249324/55592379-3d37d400-5706-11e9-85bd-ae79cf593006.png)

This happened before and seems to be a pattern with chrome. I didn't report because I thought it was a minor issue. However this time, I got errors

```
registerEventsMessage called 
ial.js:4459 ready: before call parse for last time Object
:7500/agent/3/action/22:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
:7500/agent/3/keyword/22:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:7500/agent/3/keyword/21:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:7500/agent/3/keyword/20:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:7500/agent/3/keyword/21:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:7500/agent/3/keyword/22:1 Failed to load resource: the server responded with a status of 404 (Not Found)
5vendors~main.06513758b5b9bbf835f0.chunk.js:33 TypeError: Cannot read property 'keywordName' of undefined
    at 18.ac89480651846f13fafb.chunk.js:1
    at Mo (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at ha (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at pa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Xa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at qa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Va (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Wa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at va (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Object.enqueueSetState (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
Io @ vendors~main.06513758b5b9bbf835f0.chunk.js:33
vendors~main.06513758b5b9bbf835f0.chunk.js:117 uncaught at A TypeError: Cannot read property 'keywordName' of undefined
    at http://localhost:3000/18.ac89480651846f13fafb.chunk.js:1:13409
    at Mo (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:64332)
    at ha (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:77306)
    at pa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:77613)
    at Xa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:81161)
    at qa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:80673)
    at Va (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:80499)
    at Wa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:79872)
    at va (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:79104)
    at Object.enqueueSetState (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:54640)
```

From my console on git bash I noticed something:

```
api_1            | { ValidationError: child "slots" fails because ["slots" at position 0 fails because [child "remainingLife" fails because ["remainingLife" must be a number]]]
api_1            |     at Object.exports.process (/usr/src/app/node_modules/joi/lib/errors.js:196:19)
api_1            |     at internals.Object._validateWithOptions (/usr/src/app/node_modules/joi/lib/types/any/index.js:675:31)
api_1            |     at module.exports.internals.Any.root.validate (/usr/src/app/node_modules/joi/lib/index.js:138:23)
api_1            |     at Object.internals.input (/usr/src/app/node_modules/hapi/lib/validation.js:83:63)
api_1            |     at exports.payload (/usr/src/app/node_modules/hapi/lib/validation.js:50:22)
api_1            |     at Request._lifecycle (/usr/src/app/node_modules/hapi/lib/request.js:262:62)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            |   isJoi: true,
api_1            |   name: 'ValidationError',
api_1            |   details:
api_1            |    [ { message: '"remainingLife" must be a number',
api_1            |        path: [Array],
api_1            |        type: 'number.base',
api_1            |        context: [Object] } ],
api_1            |   _object:
api_1            |    '{"actionName":"get order","slots":[{"slotName":"toppings","uiColor":"#1976d2","keyword":"topppings","keywordId":0,"isList":false,"isRequired":false,"textPrompts":[],"remainingLife":""}],"responses":[{"textResponse":"Ok we\'ll get your pizza ready.","actions":[]},{"textResponse":"Sure, we\'ll ahve the pizza out to you soon","actions":[]},{"textResponse":"Processing order, and will be on the way, thanks!","actions":[]}],"useWebhook":false,"usePostFormat":false,"creationDate":"1554414294000","modificationDate":"1554415770000"}',
api_1            |   annotate: [Function],
api_1            |   isBoom: true,
api_1            |   isServer: false,
api_1            |   data: null,
api_1            |   output:
api_1            |    { statusCode: 400,
api_1            |      payload:
api_1            |       { statusCode: 400,
api_1            |         error: 'Bad Request',
api_1            |         message:
api_1            |          'child "slots" fails because ["slots" at position 0 fails because [child "remainingLife" fails because ["remainingLife" must be a number]]]',
api_1            |         validation: [Object] },
api_1            |      headers: {} },
api_1            |   reformat: [Function] }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Keywordid=[22] not found' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Keywordid=[21] not found' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Keywordid=[20] not found' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Keywordid=[21] not found' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Keywordid=[22] not found' },
api_1            |   message: null }
```
Step 5.21 on script

From the git bash console, I guess its just telling me that there wasn't values into the slots when saving, so probably not a bug/error as far as with the code.

It is my opinion that Firefox is most stable, at least for this particulate release.

- Did you download a release or pull from Master? Which release?
Release 21.1
- What operating system are you running?
win 10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Chrome

**Comment by wrathagom** [comment]
we're handling this now.

**Comment by RussellSPG** [comment]
Ok, so I'll que this for testing on the next release after 22.0?
