### ISSUE TITLE
Chrome: Again blank page after hitting exit in response on action screen

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#672]
Please describe the issue you are having here and answer the question below.

Again, I got a blank page after hitting save and exit(or train) I forget which, when in action screen in response tab. Chrome is really seeming to be the most unstable browser for Articulate as of this release. When I try to reproduce, it doesn't crash, or go to blank page, so its really just random behavior.

Errors in browser console:

```
registerEventsMessage called 
ial.js:4459 ready: before call parse for last time Object
5vendors~main.06513758b5b9bbf835f0.chunk.js:33 TypeError: Cannot read property 'keywordName' of undefined
    at 18.ac89480651846f13fafb.chunk.js:1
    at Mo (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at ha (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at pa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Xa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at qa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Va (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Wa (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at va (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
    at Object.enqueueSetState (vendors~main.06513758b5b9bbf835f0.chunk.js:33)
Io @ vendors~main.06513758b5b9bbf835f0.chunk.js:33
vendors~main.06513758b5b9bbf835f0.chunk.js:117 uncaught at A TypeError: Cannot read property 'keywordName' of undefined
    at http://localhost:3000/18.ac89480651846f13fafb.chunk.js:1:13409
    at Mo (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:64332)
    at ha (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:77306)
    at pa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:77613)
    at Xa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:81161)
    at qa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:80673)
    at Va (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:80499)
    at Wa (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:79872)
    at va (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:79104)
    at Object.enqueueSetState (http://localhost:3000/vendors~main.06513758b5b9bbf835f0.chunk.js:33:54640)
D @ vendors~main.06513758b5b9bbf835f0.chunk.js:117
```

Did not notice any errors in git bash. Just a bunch of POST from parse results in Rasa.

It also may be worth noting that it didn't save the edit I made, crash didn't happen from script I was fixing a syntex error in the handle bars so I did the appropriate change for the yes value. Didn't save:

![image](https://user-images.githubusercontent.com/42249324/55597706-e2f63d80-571c-11e9-8165-7771f7f70c55.png)

- Did you download a release or pull from Master? Which release?
release 21.1
- What operating system are you running?
win 10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Chrome

**Comment by wrathagom** [comment]
Given this was the same action as the previous issue you created where there was a slot validation issue I am going to say they're related and that by solving the slot problem we addressed this as well.

**Comment by RussellSPG** [comment]
Yes
