### ISSUE TITLE
unhandled error when creating saying via API

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#749]
I am testing different ways to use the API, and trying to POST the below caused a 500 error. this is on a fresh agent with only the weather category imported. Yes I know the payload isn't right, but it still shouldn't cause a 500.

```
POST http://localhost:7500/agent/3/category/6/saying
{
  "userSays": "how's the weather in Louisville",
  "keywords": [
    {
      "value": "Louisville",
      "keyword": "string",
      "keywordId": 0,
      "start": 21,
      "end": 31
    }
  ]
}
```

```
api_1            | { error:
api_1            |    TypeError: Cannot read property 'indexOf' of undefined
api_1            |        at indexOf (/usr/src/app/lib/services/action/action.split-added-old-removed-ids.service.js:15:27)
api_1            |        at arrayFilter (/usr/src/app/node_modules/lodash/lodash.js:582:11)
api_1            |        at Function.filter (/usr/src/app/node_modules/lodash/lodash.js:9175:14)
api_1            |        at ActionService.filter (/usr/src/app/lib/services/action/action.split-added-old-removed-ids.service.js:13:28)
api_1            |        at ActionService.apply [as splitAddedOldRemovedIds] (/usr/src/app/lib/services/action.services.js:20:40)
api_1            |        at AgentService.splitAddedOldRemovedIds (/usr/src/app/lib/services/agent/agent.upsert-saying-in-category.service.js:78:41)
api_1            |        at Generator.next (<anonymous>)
api_1            |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.upsert-saying-in-category.service.js:15:103)
api_1            |        at _next (/usr/src/app/lib/services/agent/agent.upsert-saying-in-category.service.js:17:194)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
```

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/afc952ff6637805c035469f044abf06c1428c2b3
