### ISSUE TITLE
Screen goes blank (with console error) when clicking Exit from action screen.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#764]
### Issues
Screen is blank with the URL: http://localhost:3000/agent/5/dialogue?filter=undefined&page=undefined&tab=sayings, with a blank screen again.

Got an error:

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

From Git bash:

```
api_1            |     Error: handler method did not return a value, a promise, or throw an error
api_1            |     at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:52:29)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            | Debug: internal, implementation, error
api_1            |     Error: handler method did not return a value, a promise, or throw an error
api_1            |     at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:52:29)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
elasticsearch_1  | [2019-05-23T10:04:40,401][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
api_1            | Debug: internal, implementation, error
api_1            |     Error: handler method did not return a value, a promise, or throw an error
api_1            |     at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:52:29)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
elasticsearch_1  | [2019-05-23T10:05:10,409][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:05:40,416][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:06:10,426][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:06:40,438][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:07:10,445][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:07:40,453][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:08:10,461][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:08:40,470][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:09:10,478][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:09:40,485][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:10:10,495][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:10:40,502][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node
elasticsearch_1  | [2019-05-23T10:11:10,511][INFO ][o.e.c.r.a.DiskThresholdMonitor] [kGcxbRv] low disk watermark [85%] exceeded on [kGcxbRvHT62S--5NN7q8kQ][kGcxbRv][/usr/share/elasticsearch/data/nodes/0] free: 15.8gb[13.3%], replicas will not be assigned to this node

```
Step 1.25 on Break Script v22.0
- Did you download a release or pull from Master? Which release?
release
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF
----

**Comment by RussellSPG** [comment]
couldn't reproduce

**Comment by wrathagom** [comment]
How did it happen?

**Comment by RussellSPG** [comment]
Was creating an action right after the agent, hit the Exit button.

**Comment by wrathagom** [comment]
I think this is related to your own Docker instance. Can you reset Docker data? On Mac it looks like this:

![image](https://user-images.githubusercontent.com/1779894/60128930-d86aa380-9761-11e9-90ec-86adbaaf10f4.png)
