### ISSUE TITLE
Webhooks on default fallbacks seem to break the default fallback responses.

### ISSUE THREAD

**Issue by cesarandreslopez** [samtecspg/articulate#866]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
From Master as of August 15th morning
- What operating system are you running?
Ubuntu 18.04 - Docker compose
- Are you running locally or in the cloud?
Locally
- Which browser are you using?
Chrome

-----------------------
Great job guys! I've been playing around with articulate for a while and I'm quite impressed!

Now for the report: 

When a webhook is set on the default fallback, no answer will be resolved and an error will appear:

`
{ error:
ReferenceError: MODEL_AGENT is not defined
at AgentService.MODEL_AGENT (/usr/src/app/lib/services/agent/agent.converse-generate-response-fallback.service.js:12:28)
at Generator.next (<anonymous>)
at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse-generate-response-fallback.service.js:7:103)
at _next (/usr/src/app/lib/services/agent/agent.converse-generate-response-fallback.service.js:9:194)
at /usr/src/app/lib/services/agent/agent.converse-generate-response-fallback.service.js:9:364
at new Promise (<anonymous>)
at AgentService.<anonymous> (/usr/src/app/lib/services/agent/agent.converse-generate-response-fallback.service.js:9:97)
at AgentService.<anonymous> (/usr/src/app/lib/services/agent/agent.converse-generate-response-fallback.service.js:1:1)
at apply (/usr/src/app/lib/services/agent.services.js:260:55)
at Generator.next (<anonymous>),
message: null }
Debug: handler, error
`

**Comment by dcalvom** [comment]
Thanks for your report. We are going to check what is happening

**Comment by dcalvom** [comment]
@cesarandreslopez I think this https://github.com/samtecspg/articulate/commit/a6dc1781f84f98df627cad71c8772b2721aa7830 will fix it.

Could you try again and report back

**Comment by cesarandreslopez** [comment]
@dcalvom I can confirm that this issue was resolved. Thank you!

Looking forward to contributing to this project as I gain more understanding of it.
