### ISSUE TITLE
Import of some categories fails

### ISSUE THREAD

**Issue by jmcnevin** [samtecspg/articulate#869]
Running `docker-compose up` on a fresh download of both 0.27.2 and 0.28.0, I am unable to import the Calculator, Currency, or Music categories into a new bot.  When I click on these categories, they don't have any dialog listed, and on import I see the following errors in my logs:

```
api_1            | { error:
api_1            |    TypeError: Cannot read property 'map' of undefined
api_1            |        at AgentService.map (/usr/src/app/lib/services/agent/agent.import-category.service.js:37:88)
api_1            |        at Generator.next (<anonymous>)
api_1            |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.import-category.service.js:17:103)
api_1            |        at _next (/usr/src/app/lib/services/agent/agent.import-category.service.js:19:194)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
api_1            | Debug: handler, error
api_1            |     Error: Cannot read property 'map' of undefined
api_1            |     at /usr/src/app/lib/routes/agent/agent.import-category.route.js:23:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.import-category.route.js:11:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.import-category.route.js:13:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            | Debug: internal, error
api_1            |     Error: Cannot read property 'map' of undefined
api_1            |     at /usr/src/app/lib/routes/agent/agent.import-category.route.js:23:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.import-category.route.js:11:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.import-category.route.js:13:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dcalvom** [comment]
Hi @jmcnevin, we're sorry about this. We put those categories as placeholders, you currently can import data from Weather or Small Talk.

I disabled the non implemented categories with this fix https://github.com/samtecspg/articulate/commit/365ac7dd7b365bc0047f0aef7251c53b5e21b1cc

Please let us know any other issue you could experiment in the usage of articulate. Thanks
