### ISSUE TITLE
Deleting a category silently fails

### ISSUE THREAD

**Issue by jmcnevin** [samtecspg/articulate#870]
This is with 0.28.0.

After importing the Weather category into a new bot, I attempted to delete the category.  I see an error being reported in the logs:

```
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 400,
api_1            |      message: 'Category \'Small Talk\' is been used by 69 sayings' },
api_1            |   message: null }
api_1            | Debug: handler, error
api_1            |     Error: Category 'Small Talk' is been used by 69 sayings
api_1            |     at /usr/src/app/lib/routes/agent/agent.remove-category.route.js:29:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.remove-category.route.js:11:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.remove-category.route.js:13:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

However, this error is not reported to the UI, and nothing happens.

**Comment by wrathagom** [comment]
Errors are reported in the chat panel, you're saying nothing showed up there?

**Comment by wrathagom** [comment]
Confirmed this is working.
