### ISSUE TITLE
Agent demo categories crash /api/agent/*/converse?debug=true 500 

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#871]
Using the actual version from master branch, rebuilt and used the locally build docker images (tested building in prod and debug)

i created a bot using the two demo categories (weather and small talk)

When following the scenario on the screenshot i got an error 500 

<img width="996" alt="Capture d’écran 2019-08-18 à 00 53 30" src="https://user-images.githubusercontent.com/4228370/63218445-e978d500-c152-11e9-891c-39ea757dfdfe.png">

<img width="291" alt="Capture d’écran 2019-08-18 à 00 53 19" src="https://user-images.githubusercontent.com/4228370/63218446-e978d500-c152-11e9-9ebe-d91bd91c0d30.png">

POST http://192.168.1.33:8080/api/agent/5/converse?debug=true 500 (Internal Server Error)

```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
{ error:
   TypeError: Cannot read property 'keyword' of undefined
       at keyword (/usr/src/app/lib/services/agent/agent.converse.service.js:82:111)
       at Array.some (<anonymous>)
       at some (/usr/src/app/lib/services/agent/agent.converse.service.js:80:46)
       at Array.map (<anonymous>)
       at map (/usr/src/app/lib/services/agent/agent.converse.service.js:77:73)
       at AgentService.getActionToModify (/usr/src/app/lib/services/agent/agent.converse.service.js:196:46)
       at Generator.next (<anonymous>)
       at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse.service.js:11:103)
       at _next (/usr/src/app/lib/services/agent/agent.converse.service.js:13:194)
       at process._tickCallback (internal/process/next_tick.js:68:7),
  message: null }
Debug: handler, error 
    Error: Cannot read property 'keyword' of undefined
    at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
    at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Debug: internal, error 
    Error: Cannot read property 'keyword' of undefined
    at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
    at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

At this point i don't know if it is related to the data on the predifined categories, or if it is a more serious problem with the modifiers.

**Comment by wrathagom** [comment]
Should be fixed with https://github.com/samtecspg/articulate/commit/9708231849530aefa98f76b8595b4b284c0deb86
