### ISSUE TITLE
Open chat on small window

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#934]
On the latest version, docker linux.

When the window is small, if i click on the open chat button the content disapear and nothing happens, i have to refresh the window

Uncaught Invariant Violation: HiddenJs(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:55:15)
    at reconcileChildFibers (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12636:13)
    at reconcileChildren (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14410:28)
    at updateFunctionComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14644:3)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15637:16)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19312:12)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19352:24)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:149:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:199:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:256:31)
webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17117 The above error occurred in the <HiddenJs> component:
    in HiddenJs (created by WithWidth(HiddenJs))
    in WithWidth(HiddenJs) (created by WithTheme(WithWidth(HiddenJs)))
    in WithTheme(WithWidth(HiddenJs)) (created by Hidden)
    in Hidden (created by AppHeader)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (created by AppHeader)
    in AppHeader (created by InjectIntl(AppHeader))
    in InjectIntl(AppHeader) (created by WithStyles(InjectIntl(AppHeader)))
    in WithStyles(InjectIntl(AppHeader)) (created by Context.Consumer)
    in Route (created by withRouter(WithStyles(InjectIntl(AppHeader))))
    in withRouter(WithStyles(InjectIntl(AppHeader))) (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by withSaga(Connect(App)))
    in withSaga(Connect(App)) (created by Context.Consumer)
    in Route (created by withRouter(withSaga(Connect(App))))
    in withRouter(withSaga(Connect(App))) (created by _class)
    in _class
    in MuiThemeProviderOld
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction
    in IntlProvider (created by LanguageProvider)
    in LanguageProvider (created by ConnectFunction)
    in ConnectFunction
    in Provider
    in div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17117
webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20312 Uncaught Invariant Violation: HiddenJs(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:55:15)
    at reconcileChildFibers (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12636:13)
    at reconcileChildren (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14410:28)
    at updateFunctionComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14644:3)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15637:16)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19312:12)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19352:24)
    at renderRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19435:7)
    at performWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20342:7)
    at performWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20254:7)

**Comment by dakavisa** [comment]
Hi @mordebip , I tried this with last release and current master, in mac and ubuntu, chrome firefox and safari with every breakpoint value: xs, sm, md, lg, xl, and for every tab in dialogue page and could not reproduce it.

- Is there any specific set of steps that trigger this that you can provide (tab selected, state of the agent, previous actions)? 
- Are you seeing this everytime the window is small?
- Which browser are you using?
- Any other detail would be helpful to reproduce it.

**Comment by mordebip** [comment]
it can be due to the fact that i tried updating multiple packages (on the ui and the api side)
i will redo a clean clone from the repo and remake a full test
