### ISSUE TITLE
Unable to run articulate when deployed on EC2.

### ISSUE THREAD

**Issue by tanmay31081992** [samtecspg/articulate#935]
I am able to train my bot but while testing or deploying I am getting 404 error.

**Comment by tanmay31081992** [comment]
Following is the error log

> { error:
api_1            |    Error: not found
api_1            |        at CreatedClass.getHashAll (/usr/src/app/node_modules/nohm/ts/model.ts:1328:13)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: 'Category id=[1,2,3]' }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Category id=[1,2,3]' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Category id=[1,2,3]' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Category id=[1,2,3]' },
api_1            |   message: null }
api_1            | Debug: handler, error
api_1            |     Error: Category id=[1,2,3]
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1          | 115.110.193.46 - - [09/Oct/2019:09:06:28 +0000] "POST /api/agent/1/converse?debug=true HTTP/1.1" 404 70 "http://54.213.90.199:8080/agent/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" "-"

>

**Comment by tanmay31081992** [comment]
The required port was not opened :(
