### ISSUE TITLE
opening an slot

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#951]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

I create quick answer in slot
this is the log
   message: null }
api_1_b6eaabf8ea04 | Debug: handler, error
api_1_b6eaabf8ea04 |     Error: Cannot read property 'slots' of undefined
api_1_b6eaabf8ea04 |     at Object.<anonymous> (/usr/src/app/lib/channels/chat-widget/post.js:33:14)
api_1_b6eaabf8ea04 |     at Generator.throw (<anonymous>)
api_1_b6eaabf8ea04 |     at asyncGeneratorStep (/usr/src/app/lib/channels/chat-widget/post.js:7:103)
api_1_b6eaabf8ea04 |     at _throw (/usr/src/app/lib/channels/chat-widget/post.js:9:291)
api_1_b6eaabf8ea04 | Debug: internal, error
api_1_b6eaabf8ea04 |     Error: Cannot read property 'slots' of undefined
api_1_b6eaabf8ea04 |     at Object.<anonymous> (/usr/src/app/lib/channels/chat-widget/post.js:33:14)
api_1_b6eaabf8ea04 |     at Generator.throw (<anonymous>)
api_1_b6eaabf8ea04 |     at asyncGeneratorStep (/usr/src/app/lib/channels/chat-widget/post.js:7:103)
api_1_b6eaabf8ea04 |     at _throw (/usr/src/app/lib/channels/chat-widget/post.js:9:291)
nginx_1_6d507e6eb4b4 | 10.33.0.150 - - [30/Oct/2019:10:20:42 +0000] "POST /api/connection/01e75070-fafc-11e9-b5b0-db40f8f03c9e/external HTTP/1.1" 500 96 "http://10.33.0.44/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"
rasa_1_20c47e12775d | 2019-10-30 10:20:45+0000 [-] "172.18.0.6" - - [30/Oct/2019:10:20:44 +0000] "POST /parse HTTP/1.1" 200 219 "-" "axios/0.18.0"
api_1_b6eaabf8ea04 | { error:
api_1_b6eaabf8ea04 |    TypeError: Cannot read property 'slots' of undefined
api_1_b6eaabf8ea04 |        at slots (/usr/src/app/lib/services/agent/agent.converse.service.js:80:40)
api_1_b6eaabf8ea04 |        at Array.map (<anonymous>)
api_1_b6eaabf8ea04 |        at map (/usr/src/app/lib/services/agent/agent.converse.service.js:77:73)
api_1_b6eaabf8ea04 |        at AgentService.getActionToModify (/usr/src/app/lib/services/agent/agent.converse.service.js:226:46)
api_1_b6eaabf8ea04 |        at Generator.next (<anonymous>)
api_1_b6eaabf8ea04 |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse.service.js:11:103)
api_1_b6eaabf8ea04 |        at _next (/usr/src/app/lib/services/agent/agent.converse.service.js:13:194)
api_1_b6eaabf8ea04 |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1_b6eaabf8ea04 |   message: null }
api_1_b6eaabf8ea04 | Debug: handler, error
api_1_b6eaabf8ea04 |     Error: Cannot read property 'slots' of undefined
api_1_b6eaabf8ea04 |     at Object.<anonymous> (/usr/src/app/lib/channels/chat-widget/post.js:33:14)
api_1_b6eaabf8ea04 |     at Generator.throw (<anonymous>)
api_1_b6eaabf8ea04 |     at asyncGeneratorStep (/usr/src/app/lib/channels/chat-widget/post.js:7:103)
api_1_b6eaabf8ea04 |     at _throw (/usr/src/app/lib/channels/chat-widget/post.js:9:291)
api_1_b6eaabf8ea04 |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1_b6eaabf8ea04 | Debug: internal, error
api_1_b6eaabf8ea04 |     Error: Cannot read property 'slots' of undefined
api_1_b6eaabf8ea04 |     at Object.<anonymous> (/usr/src/app/lib/channels/chat-widget/post.js:33:14)
api_1_b6eaabf8ea04 |     at Generator.throw (<anonymous>)
api_1_b6eaabf8ea04 |     at asyncGeneratorStep (/usr/src/app/lib/channels/chat-widget/post.js:7:103)
api_1_b6eaabf8ea04 |     at _throw (/usr/src/app/lib/channels/chat-widget/post.js:9:291)
api_1_b6eaabf8ea04 |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1_6d507e6eb4b4 | 10.33.0.150 - - [30/Oct/2019:10:20:45 +0000] "POST /api/connection/01e75070-fafc-11e9-b5b0-db40f8f03c9e/external HTTP/1.1" 500 96 "http://10.33.0.44/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"

- Did you download a release or pull from Master? Which release?0.29
- What operating system are you running?CentOS X64
- Are you running locally or in the cloud?locally VMWARE
- Which browser are you using?firefox (widget)

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by aermike** [comment]
wrong definition
I corected it and works
